{
	"version": 1737710342,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/jada-sheet0.png",
		"images/jada-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"images/sprite2-sheet3.png",
		"images/sprite2-sheet4.png",
		"images/sprite2-sheet5.png",
		"images/sprite2-sheet6.png",
		"images/sprite2-sheet7.png",
		"images/pickchris-sheet0.png",
		"images/pickwill-sheet0.png",
		"images/pick-sheet0.png",
		"images/slap-sheet0.png",
		"images/sprite11sheet-sheet0.png",
		"images/tiledbackground.png",
		"images/particles.png",
		"images/sprite3-sheet0.png",
		"media/puch 1.m4a",
		"media/puch 1.ogg",
		"media/puch 2.m4a",
		"media/puch 2.ogg",
		"media/puch 3.m4a",
		"media/puch 3.ogg",
		"media/puch 4.m4a",
		"media/puch 4.ogg",
		"media/chris 1.m4a",
		"media/chris 1.ogg",
		"media/chris 2.m4a",
		"media/chris 2.ogg",
		"media/chris 3.m4a",
		"media/chris 3.ogg",
		"media/chris 4.m4a",
		"media/chris 4.ogg",
		"media/will 1.m4a",
		"media/will 1.ogg",
		"media/will 2.m4a",
		"media/will 2.ogg",
		"media/will 3.m4a",
		"media/will 3.ogg",
		"media/will 4.m4a",
		"media/will 4.ogg",
		"media/will vs. chris bgm.m4a",
		"media/will vs. chris bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}